name: tests
on: [push, pull_request]
jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: ClamAV setup
        run: docker-compose up -d
      - name: Sleep 60 seconds
        uses: juliangruber/sleep-action@v1
        with:
          time: 60s
      - name: Install dependencies
        run: composer update -n
      - name: Run tests
        run: vendor/bin/phpunit
